openapi: 3.0.0
info:
  title: Chat Core Api
  description: API for interacting with various chatbot personas
  version: 1.0.0
servers:
  - url: 'https://localhost/v1'
  - url: 'http://localhost/v1'
paths:
  /chat/case:
    post:
      summary: Respond to a chat case
      description: Allow user to send message and receive response from chatbot based on the personas
      operationId: reply_chat_case
      tags:
        - Chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Chat Response Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRespond'
              examples:
                normal:
                  summary: Normal Bot Response
                  value:
                    messages: "こんにちは。認知症の方に起きたことを教えていただければ、どのような対応方法が好ましいか、過去の統計情報からお答えできます 起きたことの例 ・薬を飲むことを忘れてしまう・さっき話したことを、何度も繰り返す"
                friend:
                  summary: Friend Bot Response
                  value:
                    message: "こんにちは。認知症の方に起きたことを教えていただければ、どのような対応方法が好ましいか、過去の統計情報からお答えできます 起きたことの例 ・薬を飲むことを忘れてしまう・さっき話したことを、何度も繰り返す"
                doctor:
                  summary: Doctor Bot Response
                  value:
                    message: "こんにちは。認知症の方に起きたことを教えていただければ、どのような対応方法が好ましいか、過去の統計情報からお答えできます 起きたことの例 ・薬を飲むことを忘れてしまう・さっき話したことを、何度も繰り返す"
        '400':
          description: Bad Request due to invalid input
        '401':
          description: Unauthorized access
        '500':
          description: Internal Server Error
      security:
        - ApiKeyAuth: []
tags:
  - name: Chat
    description: API for Chat Interface
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-KEY
      in: header
  schemas:
    ChatRequest:
      type: object
      title: Chat Request
      required:
        - message
        - bot_style
      properties:
        message:
          example: "私はよく薬を飲むのを忘れてしまいます。"
          type: string
          description: User message
        bot_style:
          enum:
            - normal
            - friend
            - doctor
          example: normal
          type: string
        messages:
          type: array
          description: A list of previous messages from the conversation
          items:
            $ref: '#/components/schemas/Message'
    ChatRespond:
      type: object
      title: Chat Response
      properties:
        message:
          type: string
          example: "薬を定期的に服用することは重要です。毎日のリマインダーを設定すると役立つかもしれません。"
          description: Response message from the chatbot
    Message:
      type: object
      title: Message
      required:
        - role
        - message
      properties:
        role:
          description: The role of the message sender
          type: string
          enum:
            - system
            - bot
            - user
          example: user
        message:
          type: string
          description: The content of the message
          example: "私はよく薬を飲むのを忘れてしまいます。"
